[build]
  # Static site - no build command needed
  publish = "."

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special cache settings for HTML
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  # Redirect any 404s to index.html for single page app behavior
  from = "/*"
  to = "/index.html"
  status = 404