module.exports = {
  source: [
    'tokens/global/**/*.json',
    'tokens/semantic/**/*.json'
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        options: {
          showFileHeader: true,
          fileHeader: () => [
            '==========================================================================',
            'DESIGN TOKENS - Generated by Style Dictionary', 
            'DO NOT EDIT DIRECTLY - This file is auto-generated',
            '=========================================================================='
          ]
        }
      }]
    },
    'theme-light': {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      source: ['tokens/themes/light.json'],
      files: [{
        destination: 'theme-light.css',
        format: 'css/variables',
        options: {
          showFileHeader: true,
          fileHeader: () => [
            '==========================================================================',
            'LIGHT THEME TOKENS - Generated by Style Dictionary', 
            'DO NOT EDIT DIRECTLY - This file is auto-generated',
            '=========================================================================='
          ]
        }
      }]
    },
    'theme-dark': {
      transformGroup: 'css',
      buildPath: 'tokens/build/',
      source: ['tokens/themes/dark.json'],
      files: [{
        destination: 'theme-dark.css',
        format: 'css/variables',
        options: {
          showFileHeader: true,
          fileHeader: () => [
            '==========================================================================',
            'DARK THEME TOKENS - Generated by Style Dictionary', 
            'DO NOT EDIT DIRECTLY - This file is auto-generated',
            '=========================================================================='
          ]
        }
      }]
    }
  }
};